### ISSUE TITLE
Chainweb-data fill always causes ResponseTimeout on the node

### ISSUE THREAD

**Issue by trendzetter** [kadena-io/chainweb-data#167]
Trying to fill up the chainweb-data using a local node. The node is configured with the parameters specified in [node-config-for-chainweb-data.yaml](https://github.com/kadena-io/chainweb-data/blob/master/node-config-for-chainweb-data.yaml). No error is shown in the chainweb-node log. Is there any other data I can provide to troubleshoot the issue?

```
chainweb-data-2.3.0$ chainweb-data fill --service-host=localhost --dbstring="host=localhost dbname=chainweb port=5432 user=chainweb password=x"
2023-10-29T18:39:33.289Z [Info] [] Using database: PGString "host=localhost dbname=chainweb port=5432 user=chainweb password=x"
2023-10-29T18:39:33.289Z [Info] [] Service API: http://localhost:1848
2023-10-29T18:39:33.312Z [Info] [] No migrations to run
2023-10-29T18:39:33.363Z [Info] [] The DB schema is compatible with the ORM definition.
2023-10-29T18:39:33.363Z [Info] [] DB Tables Initialized
2023-10-29T18:39:33.476Z [Info] [] Filling 78 gaps and 75489252 blocks
2023-10-29T18:40:03.477Z [Info] [] Progress: 6840/75489252 (0.01%), ~91 hours remaining at 228 current items per second (228 overall average).
chainweb-data: HttpExceptionRequest Request {
  host                 = "localhost"
  port                 = 1848
  secure               = False
  requestHeaders       = [("content-type","application/json")]
  path                 = "/chainweb/0.0/mainnet01/chain/9/payload/outputs/batch"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 ResponseTimeout

```

**Comment by enobayram** [comment]
Hi @trendzetter, thank you for opening this issue. What happens when you rerun the fill operation right after this failure, does it make some more progress before timing out again?

Would mind checking the system resource utilization (CPU/RAM) while you're running the fill operation and also at the time that the timeout error occurs.

**Comment by trendzetter** [comment]
It makes about as much progress as the first attempt, always 1 line of progress with only slightly varying numbers.
The chainweb-data process first peaks at about 500% chainweb-data and then fluctuates around 250% cpu and less than 5% mem. chainweb-node uses only 10-30% CPU and 13% mem.. The node continues to be accessible for other processes as far as I can see, I tried running a script that uses the node in parallel and it continues to function correctly. I'm not seeing processes killed off.
My own hypothesis of what happens is that chainweb-data might have a sensitive time-out and/or some throttling occurs at the node because it hits a limit.
I am currently experimenting with [bento](https://github.com/ThinEdgeLabs/bento) which has some functional overlap with chainweb-data. Its not as fast in filling but it doesn't show or halts on timeout errors.

**Comment by trendzetter** [comment]
@enobayram the issue is because I moved my node db off ssd storage onto HDD, I did that because the database was becoming too big and I couldn't do live backups anymore. the node kept working but it couldn't handle the chainweb-data fill operation apparently.  I tested with moving it back onto ssd and the issue is no more.

**Comment by enobayram** [comment]
@trendzetter thank you very much for digging further and reporting back. This makes a lot of sense, it's not surprising that chainweb-data would overwhelm the node when the node db is on an HDD, also explains why I have never encountered this. It's still curious that the `chainweb-data` process is the one that's consuming all that CPU, so I'll keep this peculiarity in mind in case there's some other performance issue lurking here.

Would you be OK with closing this issue? Ideally `chainweb-data` would adapt to the slow performance of the node in this setting so that the `fill` hums along albeit slowly, but I'm not sure this ticket is the right place to track that.

**Comment by trendzetter** [comment]
I'll close the ticket as my issue has been resolved and you have been made aware of possible this user environment related problem.
