### ISSUE TITLE
Increasing CPU and memory consumption over time

### ISSUE THREAD

**Issue by blazesal** [kadena-io/chainweb-data#81]
### Concern
When running `chainweb-data` application over a long period of time CPU and memory consumption increase. I am worried that eventually, it will result in the degradation of the system's performance.
May I please get the explanation of the observed behavior?

![chainweb-data_cpu_1d](https://user-images.githubusercontent.com/104318737/174125258-d7d211ef-13c1-4793-bf3d-2469ebc12258.png)
![chainweb-data_cpu-30d](https://user-images.githubusercontent.com/104318737/174125260-36e1787b-bf57-4408-868e-3bbcecd69a3c.png)
![chainweb-data_cpu](https://user-images.githubusercontent.com/104318737/174125262-079fd02c-8802-4dcb-9e8c-693748ffc278.png)

**Comment by enobayram** [comment]
@blazesal thank you for opening this ticket. I want to let you know that we'll turn our focus to `chainweb-data`'s performance right after releasing the new features that are about to be merged.

**Comment by enobayram** [comment]
@blazesal Thanks again for opening this ticket. I believe this performance issue should be fixed in the recent [2.2.0 release](https://github.com/kadena-io/chainweb-data/releases/tag/v2.2.0). I would appreciate if you could upgrade to 2.2.0 and check if it does indeed resolve it for you. Otherwise, I'll close this ticket in a week.

**Comment by enobayram** [comment]
Closing this ticket since I believe it already got fixed by #148 as part of the 2.2.0 release
